version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      # переменная должна называться POSTGRES_DB
      # https://hub.docker.com/_/postgres
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: js-container
    ports:
      - '9999:9999'